### ISSUE TITLE
Deno.land Readme

### ISSUE THREAD

**Issue by jeff-hykin** [Aplet123/iterplus#5]
just a heads up, the readme doesn't show up on deno.land.

I'm guessing that for deno.land you picked for it to just use the `src/` directory, which unfortunately means a readme needs to be in the src directory. I know because I screwed it up on one of my libraries.

The easiest workaround I've found is to hardlink the file; which will just show up as a duplicate on github but at least means you only need to edit one file to update both.

**Comment by Aplet123** [comment]
Thanks, I've fixed it.
